# Домашнее задание 1

Все задания ниже имеют равный вес.

## Описание данных

В папке Data находится информация о студентах. Всего 10 групп студентов.  
Файлы делятся на две категории:
*   `Students_info_i` - информация о студентах из группы `i`
*   `Students_marks_i` - оценки студентов из группы `i` за экзамены

Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут:

 https://www.kaggle.com/residentmario/renaming-and-combining#Combining

## Практика

In [ ]:
# импортируем библиотеку Pandas
import pandas as pd

In [ ]:
%%capture
# загружаем данные
!wget https://github.com/evgpat/datasets/raw/main/students.zip

In [ ]:
# проверяем загрузку (наличие файла students.zip)
!ls -lah

total 32K
drwxr-xr-x 1 root root 4.0K Mar  5 14:37 .
drwxr-xr-x 1 root root 4.0K Mar  5 14:36 ..
drwxr-xr-x 4 root root 4.0K Feb 29 14:22 .config
drwxr-xr-x 1 root root 4.0K Feb 29 14:23 sample_data
-rw-r--r-- 1 root root  16K Mar  5 14:37 students.zip

In [ ]:
# разархивируем данные
!unzip students.zip

Archive:  students.zip
   creating: students/
  inflating: students/Students_info_0.csv
  inflating: students/Students_info_1.csv
  inflating: students/Students_info_2.csv
  inflating: students/Students_info_3.csv
  inflating: students/Students_info_4.csv
  inflating: students/Students_info_5.csv
  inflating: students/Students_info_6.csv
  inflating: students/Students_info_7.csv
  inflating: students/Students_info_8.csv
  inflating: students/Students_info_9.csv
  inflating: students/Students_marks_0.csv
  inflating: students/Students_marks_1.csv
  inflating: students/Students_marks_2.csv
  inflating: students/Students_marks_3.csv
  inflating: students/Students_marks_4.csv
  inflating: students/Students_marks_5.csv
  inflating: students/Students_marks_6.csv
  inflating: students/Students_marks_7.csv
  inflating: students/Students_marks_8.csv
  inflating: students/Students_marks_9.csv

In [ ]:
# смотрим что получилось
!ls -lah students

total 128K
drwxrwxr-x 2 root root 4.0K Jul 25  2023 .
drwxr-xr-x 1 root root 4.0K Mar  5 14:38 ..
-rw-rw-r-- 1 root root 5.8K Jan 17  2021 Students_info_0.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_1.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_2.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_3.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_4.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_5.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_6.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_7.csv
-rw-rw-r-- 1 root root 5.9K Jan 17  2021 Students_info_8.csv
-rw-rw-r-- 1 root root 6.0K Jan 17  2021 Students_info_9.csv
-rw-rw-r-- 1 root root 1.4K Jan 17  2021 Students_marks_0.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_1.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_2.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_3.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_4.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_5.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_6.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_7.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_8.csv
-rw-rw-r-- 1 root root 1.5K Jan 17  2021 Students_marks_9.csv

### Задание 1

Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата

In [ ]:
# ваш код здесь

st_info = pd.DataFrame()
grades = pd.DataFrame()

for i in range(10):
    st_info = pd.concat(
        [st_info, pd.read_csv(f"students/Students_info_{i}.csv")], ignore_index=True
    )
    grades = pd.concat(
        [grades, pd.read_csv(f"students/Students_marks_{i}.csv")], ignore_index=True
    )

In [ ]:
# смотрим структуру датафреймов, чтобы определить, есть ли общие колонки для слияния

st_info.head()

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group
0,0,female,group B,bachelor's degree,standard,none,group1
1,1,female,group C,some college,standard,completed,group1
2,2,female,group B,master's degree,standard,none,group1
3,3,male,group A,associate's degree,free/reduced,none,group1
4,4,male,group C,some college,standard,none,group1

In [ ]:
grades.head()

   index  math score  reading score  writing score
0      0          72             72             74
1      1          69             90             88
2      2          90             95             93
3      3          47             57             44
4      4          76             78             75

In [ ]:
df = pd.merge(st_info, grades, on="index")

# df = st_info.set_index('index').join(grades.set_index('index'))
# колонка 'index' по умолчанию будет индексом

df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

### Задание 2

Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы

In [ ]:
# ваш код здесь
df = df.drop("index", axis=1)

df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

### Задание 3

Выведите на экран размеры полученной таблицы

In [ ]:
# ваш код здесь
df.shape

(1000, 9)

### Задание 4

Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
# ваш код здесь
df.describe()  # также включает перцентили 25, 50 и 75%, общее кол-во

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Задание 5

Проверьте, есть ли в таблице пропущенные значения

In [ ]:
# ваш код здесь
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   group                        1000 non-null   object
 6   math score                   1000 non-null   int64
 7   reading score                1000 non-null   int64
 8   writing score                1000 non-null   int64
dtypes: int64(3), object(6)
memory usage: 78.1+ KB

In [ ]:
# альтернативный вариант, выводит False при отсутствии пропусков, True - при наличии
null_values = df.isnull().any()

null_values

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
group                          False
math score                     False
reading score                  False
writing score                  False
dtype: bool

### Задание 6

Выведите на экран средние баллы студентов по каждому предмету (`math`, `reading`, `writing`)

In [ ]:
# ваш код здесь
math_mean = df["math score"].mean()
read_mean = df["reading score"].mean()
writ_mean = df["writing score"].mean()

print(
    f"Mean values\n\tMath: {math_mean}\n\tReading: {read_mean}\n\tWriting: {writ_mean}"
)

Mean values
	Math: 66.089
	Reading: 69.169
	Writing: 68.054

### Задание 7

Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)?

Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.

In [ ]:
# ваш код здесь
math_mean_prep = df[df["test preparation course"] == "completed"]["math score"].mean()
math_mean_noprep = df[df["test preparation course"] == "none"]["math score"].mean()

read_mean_prep = df[df["test preparation course"] == "completed"][
    "reading score"
].mean()
read_mean_noprep = df[df["test preparation course"] == "none"]["reading score"].mean()

writ_mean_prep = df[df["test preparation course"] == "completed"][
    "writing score"
].mean()
writ_mean_noprep = df[df["test preparation course"] == "none"]["writing score"].mean()

print(
    """
Math mean score:
\twith prep course: {:.3f}
\twithout prep course: {:.3f}

Reading mean score:
\twith prep course: {:.3f}
\twithout prep course: {:.3f}

Writing mean score:
\twith prep course: {:.3f}
\twithout prep course: {:.3f}
""".format(
        math_mean_prep,
        math_mean_noprep,
        read_mean_prep,
        read_mean_noprep,
        writ_mean_prep,
        writ_mean_noprep,
    )
)

# итог: по каждому предмету средний балл студентов, прошедших подготовительный курс, ощутимо выше
# => можно сказать, что подготовительный курс эффективно влияет на улучшение результатов

Math mean score:
	with prep course: 69.696
	without prep course: 64.078

Reading mean score:
	with prep course: 73.894
	without prep course: 66.534

Writing mean score:
	with prep course: 74.419
	without prep course: 64.505

### Задание 8

Выведите на экран все различные значения из столбца `lunch`

In [ ]:
# ваш код здесь
df["lunch"].unique()

array(['standard', 'free/reduced'], dtype=object)

### Задание 9

Переименуйте колонку `parental level of education` в `education`, а `test preparation course` в `test preparation` с помощью метода pandas [`rename`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html)

In [ ]:
# ваш код здесь
df = df.rename(
    columns={
        "parental level of education": "education",
        "test preparation course": "test preparation",
    }
)

df.head()

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75

### Задание 10

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Ответьте на вопросы**
* Какая доля студентов сдала экзамен по математике (passmark > 50)?
* Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
* Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:
# ваш код здесь
math_pass_rate = len(df[df["math score"] > passmark]) / len(df)

math_pass_rate

0.85

In [ ]:
# ваш код здесь
prep_sts = df[df["test preparation"] == "completed"]
math_pass_rate_prep = len(prep_sts[prep_sts["math score"] > passmark]) / len(prep_sts)

math_pass_rate_prep

0.9078212290502793

In [ ]:
# ваш код здесь
female_sts_noprep = df[(df["gender"] == "female") & (df["test preparation"] == "none")]
math_fail_rate_f_noprep = len(
    female_sts_noprep[female_sts_noprep["math score"] > passmark]
) / len(female_sts_noprep)

math_fail_rate_f_noprep

0.7664670658682635

### Задание 11

С помощью `groupby` выполните задания ниже. Также выведите время выполнения каждого из заданий.
* Для каждой этнической группы выведите средний балл за экзамен по чтению
* Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
# ваш код здесь
%%time
read_mean_score = df.groupby("race/ethnicity")["reading score"].mean()

read_mean_score

CPU times: user 1.72 ms, sys: 0 ns, total: 1.72 ms
Wall time: 4.8 ms

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [ ]:
# ваш код здесь
%%time
writ_min_score = df.groupby("education")["writing score"].min()

writ_min_score

CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 4.5 ms

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

### Задание 12

Выполните задание 11 с помощью циклов. Сравните время выполнения

In [ ]:
df.head()

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75

In [ ]:
# ваш код здесь
%%time
eth_groups = df["race/ethnicity"].unique()
read_mean_score_1 = {}

for group in eth_groups:
    read_mean_score_1[group] = df[df["race/ethnicity"] == group]["reading score"].mean()

read_mean_score_1 = sorted(read_mean_score_1.items())

read_mean_score_1

CPU times: user 4.6 ms, sys: 938 µs, total: 5.54 ms
Wall time: 5.38 ms

[('group A', 64.67415730337079),
 ('group B', 67.35263157894737),
 ('group C', 69.10344827586206),
 ('group D', 70.03053435114504),
 ('group E', 73.02857142857142)]

In [ ]:
%%time
edu_level = df["education"].unique()
writ_mean_score_1 = {}

for level in edu_level:
    writ_mean_score_1[level] = df[df["education"] == level]["writing score"].min()

writ_mean_score_1 = sorted(writ_mean_score_1.items())

writ_mean_score_1

CPU times: user 3.98 ms, sys: 841 µs, total: 4.82 ms
Wall time: 4.68 ms

[("associate's degree", 35),
 ("bachelor's degree", 38),
 ('high school', 15),
 ("master's degree", 46),
 ('some college', 19),
 ('some high school', 10)]


*Время обработки метода groupby ожидаемо ниже времени обработки циклов*

### Задание 13

Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования.  
То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выведите средний балл по каждому из предметов.

Это можно сделать с помощью сводных таблиц ([pivot_table](https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas))

In [ ]:
# ваш код здесь
mean_scores = pd.pivot_table(
    df,
    values=["math score", "reading score", "writing score"],
    index=["gender", "education"],
    aggfunc="mean",
)

mean_scores

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

### Задание 14

Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице `df` под названием `Math_PassStatus` и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
# ваш код здесь
# через функцию для минимизации копипасты
def results_breakdown(df, col, passmark=50):
    col_upd = col.replace(" score", "").capitalize()
    status_col = col_upd + "_PassStatus"
    df[status_col] = ["F" if row < passmark else "P" for row in df[col]]
    passed = df[status_col].value_counts()[
        "P"
    ]  # или df[df[status_col] == 'P'].shape[0]
    failed = df[status_col].value_counts()[
        "F"
    ]  # или df[df[status_col] == 'F'].shape[0]
    return f"Passed {col_upd}: {passed} / Failed {col_upd}: {failed}"

In [ ]:
print(results_breakdown(df, "math score"))
print(results_breakdown(df, "reading score"))
print(results_breakdown(df, "writing score"))

Passed Math: 865 / Failed Math: 135
Passed Reading: 910 / Failed Reading: 90
Passed Writing: 886 / Failed Writing: 114

In [ ]:
df  # проверка нового вида датафрейма

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P

### Задание 15

Сколько студентов успешно сдали все экзамены?

Создайте столбец `OverAll_PassStatus` и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
# ваш код здесь
df["OverAll_PassStatus"] = [
    "P" if all([row[0] == "P", row[1] == "P", row[2] == "P"]) else "F"
    for row in df[
        ["Math_PassStatus", "Reading_PassStatus", "Writing_PassStatus"]
    ].itertuples(index=False)
]

In [ ]:
# вид обновленного датафрейма
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P

In [ ]:
# c помощью лямбда функции + проверка
df["OP"] = df[["Math_PassStatus", "Reading_PassStatus", "Writing_PassStatus"]].apply(
    lambda elem: "F" if "F" in elem.values else "P", axis=1
)

df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,OP
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P,P
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P,P

In [ ]:
# удаление дубликата
df = df.drop("OP", axis=1)

### Задание 16

Переведем баллы в оценки

**Система перевода баллов в оценки**
*   [90;100] = A
*   [80;90) = B
*   [70;80) = C
*   [60;70) = D
*   [50;60) = E
*   [0;50) = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец `Grade` и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

In [ ]:
# для наглядности самовольно добавляю стоблец со средней оценкой, по моему мнению (человека, который с подобным работал 4 года), он вполне уместен и полезен
df["Avg_Score"] = (
    df[["math score", "reading score", "writing score"]].mean(axis=1).round(2)
)

df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Avg_Score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,72.67
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,82.33
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,92.67
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,49.33
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P,94.00
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P,57.33
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P,65.00
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P,74.33
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P,83.00

In [ ]:
def GetGrade(average_mark):
    # ваш код здесь
    # создание словаря с диапазонами оценок
    grading_scale = {
        "A": (90, 100),
        "B": (80, 89),
        "C": (70, 79),
        "D": (60, 69),
        "E": (50, 59),
        "F": (0, 49),
    }
    for grade, (band_bottom, band_top) in grading_scale.items():
        if band_bottom <= float(average_mark) <= band_top:
            return grade
    return "F"
    # я не очень поняла, почему присваивание 'F' не происходит на уровне условия несмотря на то, что этот диапазон есть в словаре, но таким образом хотя бы корректно сработало в итоге


# ваш код здесь
df["Grade"] = df["Avg_Score"].apply(GetGrade)

df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Avg_Score,Grade
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,72.67,C
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,82.33,B
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,92.67,A
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,49.33,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,76.33,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P,94.00,A
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P,57.33,E
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P,65.00,D
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P,74.33,C
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P,83.00,B

*Спасибо за такую домашку! Она была суперполезная - на дисциплине Python мы вообще не дошли до ДЗ по pandas, и при самостоятельной тренировке получалось пройтись только по основам, а это ДЗ стало отличной возможностью узнать что-то новое, что действительно понадобится в аналитике*

In [ ]:
# run once
!pip install black[jupyter] --quiet
from google.colab import drive

drive.mount("/content/drive")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 42.4 MB/s eta 0:00:00

In [ ]:
# run many times
!black /content/drive/MyDrive/'Colab Notebooks'/'ML_homework_01_pandas_Kuznetsova.ipynb'

All done! ✨ 🍰 ✨
1 file left unchanged.